/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Campus {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(rename = "is_activated", skip_serializing_if = "Option::is_none")]
    pub is_activated: Option<bool>,
    #[serde(rename = "is_kickoff_activated", skip_serializing_if = "Option::is_none")]
    pub is_kickoff_activated: Option<bool>,
    #[serde(rename = "webhook_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_uri: Option<Option<String>>,
    #[serde(rename = "webhook_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
}

impl Campus {
    pub fn new(id: i32, display_name: String, name: String, timezone: String) -> Campus {
        Campus {
            id,
            display_name,
            name,
            timezone,
            is_activated: None,
            is_kickoff_activated: None,
            webhook_uri: None,
            webhook_secret: None,
        }
    }
}

