/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitialPaceForm {
    #[serde(rename = "selected_pace")]
    pub selected_pace: i32,
}

impl InitialPaceForm {
    pub fn new(selected_pace: i32) -> InitialPaceForm {
        InitialPaceForm {
            selected_pace,
        }
    }
}

