/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Milestone {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<Option<String>>,
    #[serde(rename = "validated_at")]
    pub validated_at: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
}

impl Milestone {
    pub fn new(level: i32, validated_at: String, user_id: i32) -> Milestone {
        Milestone {
            id: None,
            level,
            deadline: None,
            validated_at,
            user_id,
        }
    }
}

