/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pace {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub level: Option<Option<i32>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
}

impl Pace {
    pub fn new(created_at: String, reason: String, user_id: i32) -> Pace {
        Pace {
            id: None,
            level: None,
            created_at,
            reason,
            user_id,
        }
    }
}

