/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceMatrixCreation {
    #[serde(rename = "version")]
    pub version: Box<models::PaceMatrixVersionCreation>,
    #[serde(rename = "cells")]
    pub cells: Vec<models::PaceMatrixCell>,
}

impl PaceMatrixCreation {
    pub fn new(version: models::PaceMatrixVersionCreation, cells: Vec<models::PaceMatrixCell>) -> PaceMatrixCreation {
        PaceMatrixCreation {
            version: Box::new(version),
            cells,
        }
    }
}

