/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaceMatrixCell : Representation of matrix data: for a given pace level and matrix level, gives the corresponding days.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceMatrixCell {
    #[serde(rename = "milestone")]
    pub milestone: i32,
    #[serde(rename = "pace")]
    pub pace: i32,
    #[serde(rename = "days")]
    pub days: i32,
}

impl PaceMatrixCell {
    /// Representation of matrix data: for a given pace level and matrix level, gives the corresponding days.
    pub fn new(milestone: i32, pace: i32, days: i32) -> PaceMatrixCell {
        PaceMatrixCell {
            milestone,
            pace,
            days,
        }
    }
}

