/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceMatrixVersionedCell {
    #[serde(rename = "milestone")]
    pub milestone: i32,
    #[serde(rename = "pace")]
    pub pace: i32,
    #[serde(rename = "days")]
    pub days: i32,
    #[serde(rename = "version_id")]
    pub version_id: i32,
}

impl PaceMatrixVersionedCell {
    pub fn new(milestone: i32, pace: i32, days: i32, version_id: i32) -> PaceMatrixVersionedCell {
        PaceMatrixVersionedCell {
            milestone,
            pace,
            days,
            version_id,
        }
    }
}

