/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaceMatrixVersion : Entity used to version the pace matrix (or rather it's cells)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceMatrixVersion {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
}

impl PaceMatrixVersion {
    /// Entity used to version the pace matrix (or rather it's cells)
    pub fn new(id: i32, name: String) -> PaceMatrixVersion {
        PaceMatrixVersion {
            id,
            created_at: None,
            name,
        }
    }
}

