/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaceMatrix : Class representing a pace matrix, which facilitate the manipulation of the matrix cells and data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceMatrix {
    #[serde(rename = "version")]
    pub version: Box<models::PaceMatrixVersion>,
    #[serde(rename = "cells")]
    pub cells: Vec<models::PaceMatrixCell>,
}

impl PaceMatrix {
    /// Class representing a pace matrix, which facilitate the manipulation of the matrix cells and data.
    pub fn new(version: models::PaceMatrixVersion, cells: Vec<models::PaceMatrixCell>) -> PaceMatrix {
        PaceMatrix {
            version: Box::new(version),
            cells,
        }
    }
}

