/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceSpeedUp {
    #[serde(rename = "deadline")]
    pub deadline: String,
    #[serde(rename = "common_core_eta_completion")]
    pub common_core_eta_completion: String,
}

impl PaceSpeedUp {
    pub fn new(deadline: String, common_core_eta_completion: String) -> PaceSpeedUp {
        PaceSpeedUp {
            deadline,
            common_core_eta_completion,
        }
    }
}

