/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaceMatrixVersionCreation {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
}

impl PaceMatrixVersionCreation {
    pub fn new(name: String) -> PaceMatrixVersionCreation {
        PaceMatrixVersionCreation {
            created_at: None,
            name,
        }
    }
}

