/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageMilestone {
    #[serde(rename = "items")]
    pub items: Vec<models::Milestone>,
    #[serde(rename = "total", deserialize_with = "Option::deserialize")]
    pub total: Option<i32>,
    #[serde(rename = "page", deserialize_with = "Option::deserialize")]
    pub page: Option<i32>,
    #[serde(rename = "size", deserialize_with = "Option::deserialize")]
    pub size: Option<i32>,
    #[serde(rename = "pages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pages: Option<Option<i32>>,
}

impl PageMilestone {
    pub fn new(items: Vec<models::Milestone>, total: Option<i32>, page: Option<i32>, size: Option<i32>) -> PageMilestone {
        PageMilestone {
            items,
            total,
            page,
            size,
            pages: None,
        }
    }
}

