/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseActivateUserUsersUserIdActivatePost {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<String>,
    #[serde(rename = "cursus_begin_date")]
    pub cursus_begin_date: String,
    #[serde(rename = "matrix_version")]
    pub matrix_version: i32,
    #[serde(rename = "campus_id")]
    pub campus_id: i32,
    #[serde(rename = "pace", skip_serializing_if = "Option::is_none")]
    pub pace: Option<i32>,
    #[serde(rename = "milestone", skip_serializing_if = "Option::is_none")]
    pub milestone: Option<i32>,
    #[serde(rename = "deadline", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<String>,
    #[serde(rename = "cumulative_freeze_days", skip_serializing_if = "Option::is_none")]
    pub cumulative_freeze_days: Option<i32>,
    #[serde(rename = "is_activated", skip_serializing_if = "Option::is_none")]
    pub is_activated: Option<bool>,
    #[serde(rename = "activated_at", skip_serializing_if = "Option::is_none")]
    pub activated_at: Option<String>,
    #[serde(rename = "allow_speed_up", skip_serializing_if = "Option::is_none")]
    pub allow_speed_up: Option<bool>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "last_milestone_achieved", skip_serializing_if = "Option::is_none")]
    pub last_milestone_achieved: Option<i32>,
    #[serde(rename = "last_milestone_validated_at", skip_serializing_if = "Option::is_none")]
    pub last_milestone_validated_at: Option<String>,
    #[serde(rename = "total_added_days_before_activation", skip_serializing_if = "Option::is_none")]
    pub total_added_days_before_activation: Option<i32>,
    #[serde(rename = "freeze_days_before_activation", skip_serializing_if = "Option::is_none")]
    pub freeze_days_before_activation: Option<i32>,
    #[serde(rename = "gifted_days_before_activation", skip_serializing_if = "Option::is_none")]
    pub gifted_days_before_activation: Option<i32>,
    #[serde(rename = "total_added_days_after_activation", skip_serializing_if = "Option::is_none")]
    pub total_added_days_after_activation: Option<i32>,
    #[serde(rename = "freeze_days_after_activation", skip_serializing_if = "Option::is_none")]
    pub freeze_days_after_activation: Option<i32>,
    #[serde(rename = "gifted_days_after_activation", skip_serializing_if = "Option::is_none")]
    pub gifted_days_after_activation: Option<i32>,
    #[serde(rename = "system_days_after_activation", skip_serializing_if = "Option::is_none")]
    pub system_days_after_activation: Option<i32>,
    #[serde(rename = "deadline_days_delta_from_activation_date", skip_serializing_if = "Option::is_none")]
    pub deadline_days_delta_from_activation_date: Option<i32>,
    #[serde(rename = "pace_level", skip_serializing_if = "Option::is_none")]
    pub pace_level: Option<i32>,
    #[serde(rename = "milestone_level", skip_serializing_if = "Option::is_none")]
    pub milestone_level: Option<i32>,
    #[serde(rename = "current_milestone_deadline", skip_serializing_if = "Option::is_none")]
    pub current_milestone_deadline: Option<String>,
    #[serde(rename = "current_milestone_max_deadline", skip_serializing_if = "Option::is_none")]
    pub current_milestone_max_deadline: Option<String>,
    #[serde(rename = "common_core_max_deadline", skip_serializing_if = "Option::is_none")]
    pub common_core_max_deadline: Option<String>,
    #[serde(rename = "intra_v2_blackhole_date", skip_serializing_if = "Option::is_none")]
    pub intra_v2_blackhole_date: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ResponseActivateUserUsersUserIdActivatePost {
    pub fn new(id: i32, cursus_begin_date: String, matrix_version: i32, campus_id: i32) -> ResponseActivateUserUsersUserIdActivatePost {
        ResponseActivateUserUsersUserIdActivatePost {
            id,
            login: None,
            cursus_begin_date,
            matrix_version,
            campus_id,
            pace: None,
            milestone: None,
            deadline: None,
            cumulative_freeze_days: None,
            is_activated: None,
            activated_at: None,
            allow_speed_up: None,
            user_id: None,
            last_milestone_achieved: None,
            last_milestone_validated_at: None,
            total_added_days_before_activation: None,
            freeze_days_before_activation: None,
            gifted_days_before_activation: None,
            total_added_days_after_activation: None,
            freeze_days_after_activation: None,
            gifted_days_after_activation: None,
            system_days_after_activation: None,
            deadline_days_delta_from_activation_date: None,
            pace_level: None,
            milestone_level: None,
            current_milestone_deadline: None,
            current_milestone_max_deadline: None,
            common_core_max_deadline: None,
            intra_v2_blackhole_date: None,
            error: None,
        }
    }
}

