/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpeedUpBody {
    #[serde(rename = "should_speed_up")]
    pub should_speed_up: bool,
}

impl SpeedUpBody {
    pub fn new(should_speed_up: bool) -> SpeedUpBody {
        SpeedUpBody {
            should_speed_up,
        }
    }
}

