/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCampus {
    #[serde(rename = "is_activated", skip_serializing_if = "Option::is_none")]
    pub is_activated: Option<bool>,
    #[serde(rename = "is_kickoff_activated", skip_serializing_if = "Option::is_none")]
    pub is_kickoff_activated: Option<bool>,
    #[serde(rename = "webhook_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_uri: Option<Option<String>>,
    #[serde(rename = "webhook_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
}

impl UpdateCampus {
    pub fn new() -> UpdateCampus {
        UpdateCampus {
            is_activated: None,
            is_kickoff_activated: None,
            webhook_uri: None,
            webhook_secret: None,
        }
    }
}

