/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserActivationDryRunOutput : Sum up output of a user infos in a dry run activation. Fields are optional to be able to fill them one by one
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserActivationDryRunOutput {
    #[serde(rename = "user_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<i32>>,
    #[serde(rename = "cursus_begin_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cursus_begin_date: Option<Option<String>>,
    #[serde(rename = "last_milestone_achieved", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_milestone_achieved: Option<Option<i32>>,
    #[serde(rename = "last_milestone_validated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_milestone_validated_at: Option<Option<String>>,
    #[serde(rename = "total_added_days_before_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_added_days_before_activation: Option<Option<i32>>,
    #[serde(rename = "freeze_days_before_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub freeze_days_before_activation: Option<Option<i32>>,
    #[serde(rename = "gifted_days_before_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gifted_days_before_activation: Option<Option<i32>>,
    #[serde(rename = "total_added_days_after_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_added_days_after_activation: Option<Option<i32>>,
    #[serde(rename = "freeze_days_after_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub freeze_days_after_activation: Option<Option<i32>>,
    #[serde(rename = "gifted_days_after_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gifted_days_after_activation: Option<Option<i32>>,
    #[serde(rename = "system_days_after_activation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub system_days_after_activation: Option<Option<i32>>,
    #[serde(rename = "deadline_days_delta_from_activation_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline_days_delta_from_activation_date: Option<Option<i32>>,
    #[serde(rename = "pace_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pace_level: Option<Option<i32>>,
    #[serde(rename = "milestone_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub milestone_level: Option<Option<i32>>,
    #[serde(rename = "current_milestone_deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_milestone_deadline: Option<Option<String>>,
    #[serde(rename = "current_milestone_max_deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_milestone_max_deadline: Option<Option<String>>,
    #[serde(rename = "common_core_max_deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub common_core_max_deadline: Option<Option<String>>,
    #[serde(rename = "intra_v2_blackhole_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub intra_v2_blackhole_date: Option<Option<String>>,
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<String>>,
}

impl UserActivationDryRunOutput {
    /// Sum up output of a user infos in a dry run activation. Fields are optional to be able to fill them one by one
    pub fn new() -> UserActivationDryRunOutput {
        UserActivationDryRunOutput {
            user_id: None,
            cursus_begin_date: None,
            last_milestone_achieved: None,
            last_milestone_validated_at: None,
            total_added_days_before_activation: None,
            freeze_days_before_activation: None,
            gifted_days_before_activation: None,
            total_added_days_after_activation: None,
            freeze_days_after_activation: None,
            gifted_days_after_activation: None,
            system_days_after_activation: None,
            deadline_days_delta_from_activation_date: None,
            pace_level: None,
            milestone_level: None,
            current_milestone_deadline: None,
            current_milestone_max_deadline: None,
            common_core_max_deadline: None,
            intra_v2_blackhole_date: None,
            error: None,
        }
    }
}

