/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "login", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub login: Option<Option<String>>,
    #[serde(rename = "cursus_begin_date")]
    pub cursus_begin_date: String,
    #[serde(rename = "matrix_version")]
    pub matrix_version: i32,
    #[serde(rename = "campus_id")]
    pub campus_id: i32,
    #[serde(rename = "pace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pace: Option<Option<i32>>,
    #[serde(rename = "milestone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub milestone: Option<Option<i32>>,
    #[serde(rename = "deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<Option<String>>,
    #[serde(rename = "cumulative_freeze_days", skip_serializing_if = "Option::is_none")]
    pub cumulative_freeze_days: Option<i32>,
    #[serde(rename = "is_activated", skip_serializing_if = "Option::is_none")]
    pub is_activated: Option<bool>,
    #[serde(rename = "activated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub activated_at: Option<Option<String>>,
    #[serde(rename = "allow_speed_up", skip_serializing_if = "Option::is_none")]
    pub allow_speed_up: Option<bool>,
}

impl User {
    pub fn new(id: i32, cursus_begin_date: String, matrix_version: i32, campus_id: i32) -> User {
        User {
            id,
            login: None,
            cursus_begin_date,
            matrix_version,
            campus_id,
            pace: None,
            milestone: None,
            deadline: None,
            cumulative_freeze_days: None,
            is_activated: None,
            activated_at: None,
            allow_speed_up: None,
        }
    }
}

