/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProfile {
    #[serde(rename = "is_activated")]
    pub is_activated: bool,
    #[serde(rename = "activated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub activated_at: Option<Option<String>>,
    #[serde(rename = "milestone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub milestone: Option<Option<i32>>,
    #[serde(rename = "deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<Option<String>>,
    #[serde(rename = "cursus_begin_date")]
    pub cursus_begin_date: String,
    #[serde(rename = "eta_end_of_cursus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub eta_end_of_cursus: Option<Option<String>>,
    #[serde(rename = "probationary_period")]
    pub probationary_period: bool,
    #[serde(rename = "milestones")]
    pub milestones: Vec<models::UserMilestoneValidation>,
    #[serde(rename = "is_campus_activated")]
    pub is_campus_activated: bool,
    #[serde(rename = "pace_speed_up", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pace_speed_up: Option<Option<Box<models::PaceSpeedUp>>>,
    #[serde(rename = "pace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pace: Option<Option<i32>>,
    #[serde(rename = "end_of_cursus_max_deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_of_cursus_max_deadline: Option<Option<String>>,
}

impl UserProfile {
    pub fn new(is_activated: bool, cursus_begin_date: String, probationary_period: bool, milestones: Vec<models::UserMilestoneValidation>, is_campus_activated: bool) -> UserProfile {
        UserProfile {
            is_activated,
            activated_at: None,
            milestone: None,
            deadline: None,
            cursus_begin_date,
            eta_end_of_cursus: None,
            probationary_period,
            milestones,
            is_campus_activated,
            pace_speed_up: None,
            pace: None,
            end_of_cursus_max_deadline: None,
        }
    }
}

