/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMilestoneValidation {
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "deadline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<Option<String>>,
    #[serde(rename = "validated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub validated_at: Option<Option<String>>,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    #[serde(rename = "milestone_id")]
    pub milestone_id: i32,
}

impl UserMilestoneValidation {
    pub fn new(level: i32, user_id: i32, milestone_id: i32) -> UserMilestoneValidation {
        UserMilestoneValidation {
            level,
            deadline: None,
            validated_at: None,
            user_id,
            milestone_id,
        }
    }
}

