/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserActivationOptions {
    #[serde(rename = "dry_run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    #[serde(rename = "bypass_intra_v2_blackhole", skip_serializing_if = "Option::is_none")]
    pub bypass_intra_v2_blackhole: Option<bool>,
    #[serde(rename = "force_intra_v2_blackhole", skip_serializing_if = "Option::is_none")]
    pub force_intra_v2_blackhole: Option<bool>,
    #[serde(rename = "activation_date", skip_serializing_if = "Option::is_none")]
    pub activation_date: Option<String>,
    #[serde(rename = "max_pace", skip_serializing_if = "Option::is_none")]
    pub max_pace: Option<i32>,
}

impl UserActivationOptions {
    pub fn new() -> UserActivationOptions {
        UserActivationOptions {
            dry_run: None,
            bypass_intra_v2_blackhole: None,
            force_intra_v2_blackhole: None,
            activation_date: None,
            max_pace: None,
        }
    }
}

