/*
 * Intra v3 - Pace System
 *
 * Pace and milestone management
 *
 * The version of the OpenAPI document: 1.14.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorLocInner {
}

impl ValidationErrorLocInner {
    pub fn new() -> ValidationErrorLocInner {
        ValidationErrorLocInner {
        }
    }
}

