/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_bonus_day_settings_bonus_days_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBonusDaySettingsBonusDaysPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_campus_configuration_campus_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCampusConfigurationCampusPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_campus_webhook_campus_campus_id_webhook_webhook_type_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCampusWebhookCampusCampusIdWebhookWebhookTypeDeleteError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_bonus_days_settings_bonus_days_bonus_day_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBonusDaysSettingsBonusDaysBonusDayIdGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_campus_configuration_campus_campus_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCampusConfigurationCampusCampusIdGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_bonus_days_settings_bonus_days_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBonusDaysSettingsBonusDaysGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_campus_custom_message_campus_custom_message_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCampusCustomMessageCampusCustomMessageGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_campuses_configuration_campus_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCampusesConfigurationCampusGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_enabled_campuses_campus_enabled_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEnabledCampusesCampusEnabledGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_bonus_day_settings_bonus_days_bonus_day_id_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateBonusDaySettingsBonusDaysBonusDayIdPutError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_campus_configuration_campus_campus_id_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCampusConfigurationCampusCampusIdPatchError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_campus_pedago_mail_address_campus_campus_id_pedago_mail_address_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCampusPedagoMailAddressCampusCampusIdPedagoMailAddressPatchError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_campus_webhook_campus_campus_id_webhook_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCampusWebhookCampusCampusIdWebhookPatchError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Create a `bonus_day` configuration
pub async fn create_bonus_day_settings_bonus_days_post(
    configuration: &configuration::Configuration,
    bonus_day_create: models::BonusDayCreate,
) -> Result<Vec<models::BonusDay>, Error<CreateBonusDaySettingsBonusDaysPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_bonus_day_create = bonus_day_create;

    let uri_str = format!("{}/bonus_days", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_bonus_day_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::BonusDay&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::BonusDay&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateBonusDaySettingsBonusDaysPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Create a new configation for a campus
pub async fn create_campus_configuration_campus_post(
    configuration: &configuration::Configuration,
    campus_create: models::CampusCreate,
) -> Result<models::Campus, Error<CreateCampusConfigurationCampusPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_campus_create = campus_create;

    let uri_str = format!("{}/campus", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_campus_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Campus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Campus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateCampusConfigurationCampusPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete the webhook for a campus
pub async fn delete_campus_webhook_campus_campus_id_webhook_webhook_type_delete(
    configuration: &configuration::Configuration,
    campus_id: i32,
    webhook_type: &str,
) -> Result<models::Campus, Error<DeleteCampusWebhookCampusCampusIdWebhookWebhookTypeDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_campus_id = campus_id;
    let p_webhook_type = webhook_type;

    let uri_str = format!(
        "{}/campus/{campus_id}/webhook/{webhook_type}",
        configuration.base_path,
        campus_id = p_campus_id,
        webhook_type = crate::apis::urlencode(p_webhook_type)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Campus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Campus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteCampusWebhookCampusCampusIdWebhookWebhookTypeDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get `bonus_days` configuration for the given `bonus_day_id`
pub async fn get_bonus_days_settings_bonus_days_bonus_day_id_get(
    configuration: &configuration::Configuration,
    bonus_day_id: i32,
) -> Result<models::BonusDay, Error<GetBonusDaysSettingsBonusDaysBonusDayIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_bonus_day_id = bonus_day_id;

    let uri_str = format!(
        "{}/bonus_days/{bonus_day_id}",
        configuration.base_path,
        bonus_day_id = p_bonus_day_id
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BonusDay`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BonusDay`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBonusDaysSettingsBonusDaysBonusDayIdGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get one campus configuration on the given `campus_id`
pub async fn get_campus_configuration_campus_campus_id_get(
    configuration: &configuration::Configuration,
    campus_id: i32,
) -> Result<models::Campus, Error<GetCampusConfigurationCampusCampusIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_campus_id = campus_id;

    let uri_str = format!(
        "{}/campus/{campus_id}",
        configuration.base_path,
        campus_id = p_campus_id
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Campus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Campus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCampusConfigurationCampusCampusIdGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List all `bonus_days` configurations for the current `campus_id` given by informations of the authenticated `User`
pub async fn list_bonus_days_settings_bonus_days_get(
    configuration: &configuration::Configuration,
    milestone_id: Option<i32>,
    page: Option<i32>,
    size: Option<i32>,
) -> Result<models::PageBonusDay, Error<ListBonusDaysSettingsBonusDaysGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_milestone_id = milestone_id;
    let p_page = page;
    let p_size = size;

    let uri_str = format!("{}/bonus_days", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_milestone_id {
        req_builder = req_builder.query(&[("milestone_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PageBonusDay`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PageBonusDay`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListBonusDaysSettingsBonusDaysGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List all `custom message` from campuses configurations
pub async fn list_campus_custom_message_campus_custom_message_get(
    configuration: &configuration::Configuration,
) -> Result<
    Vec<models::CampusCustomMessage>,
    Error<ListCampusCustomMessageCampusCustomMessageGetError>,
> {
    let uri_str = format!("{}/campus/custom_message", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CampusCustomMessage&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CampusCustomMessage&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCampusCustomMessageCampusCustomMessageGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List configurations for all campuses
pub async fn list_campuses_configuration_campus_get(
    configuration: &configuration::Configuration,
    page: Option<i32>,
    size: Option<i32>,
) -> Result<models::PageCampus, Error<ListCampusesConfigurationCampusGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_page = page;
    let p_size = size;

    let uri_str = format!("{}/campus", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PageCampus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PageCampus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCampusesConfigurationCampusGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List all `enabled` campuses configurations
pub async fn list_enabled_campuses_campus_enabled_get(
    configuration: &configuration::Configuration,
) -> Result<Vec<models::Campus>, Error<ListEnabledCampusesCampusEnabledGetError>> {
    let uri_str = format!("{}/campus/enabled", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Campus&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Campus&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEnabledCampusesCampusEnabledGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Modify `bonus_day` configuration for the given `bonus_day_id`
pub async fn update_bonus_day_settings_bonus_days_bonus_day_id_put(
    configuration: &configuration::Configuration,
    bonus_day_id: i32,
    bonus_day_update: models::BonusDayUpdate,
) -> Result<models::BonusDay, Error<UpdateBonusDaySettingsBonusDaysBonusDayIdPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_bonus_day_id = bonus_day_id;
    let p_bonus_day_update = bonus_day_update;

    let uri_str = format!(
        "{}/bonus_days/{bonus_day_id}",
        configuration.base_path,
        bonus_day_id = p_bonus_day_id
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_bonus_day_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BonusDay`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BonusDay`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateBonusDaySettingsBonusDaysBonusDayIdPutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Modify configuation for a campus, based on the given `campus_id`
pub async fn update_campus_configuration_campus_campus_id_patch(
    configuration: &configuration::Configuration,
    campus_id: i32,
    campus_update: models::CampusUpdate,
) -> Result<models::Campus, Error<UpdateCampusConfigurationCampusCampusIdPatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_campus_id = campus_id;
    let p_campus_update = campus_update;

    let uri_str = format!(
        "{}/campus/{campus_id}",
        configuration.base_path,
        campus_id = p_campus_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_campus_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Campus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Campus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateCampusConfigurationCampusCampusIdPatchError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update the pedago mail address for a campus
pub async fn update_campus_pedago_mail_address_campus_campus_id_pedago_mail_address_patch(
    configuration: &configuration::Configuration,
    campus_id: i32,
    campus_mail_address_update: models::CampusMailAddressUpdate,
) -> Result<
    models::Campus,
    Error<UpdateCampusPedagoMailAddressCampusCampusIdPedagoMailAddressPatchError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_campus_id = campus_id;
    let p_campus_mail_address_update = campus_mail_address_update;

    let uri_str = format!(
        "{}/campus/{campus_id}/pedago_mail_address",
        configuration.base_path,
        campus_id = p_campus_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_campus_mail_address_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Campus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Campus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateCampusPedagoMailAddressCampusCampusIdPedagoMailAddressPatchError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update the webhook for a campus
pub async fn update_campus_webhook_campus_campus_id_webhook_patch(
    configuration: &configuration::Configuration,
    campus_id: i32,
    campus_webhook_update: models::CampusWebhookUpdate,
) -> Result<models::Campus, Error<UpdateCampusWebhookCampusCampusIdWebhookPatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_campus_id = campus_id;
    let p_campus_webhook_update = campus_webhook_update;

    let uri_str = format!(
        "{}/campus/{campus_id}/webhook",
        configuration.base_path,
        campus_id = p_campus_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_campus_webhook_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Campus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Campus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateCampusWebhookCampusCampusIdWebhookPatchError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
