/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_freeze_log_freeze_logs_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFreezeLogFreezeLogsIdGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_freeze_logs_freeze_logs_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListFreezeLogsFreezeLogsGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Get a `freeze_log` for the given `id`
pub async fn get_freeze_log_freeze_logs_id_get(
    configuration: &configuration::Configuration,
    id: i32,
) -> Result<models::FreezeLog, Error<GetFreezeLogFreezeLogsIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;

    let uri_str = format!("{}/freeze_logs/{id}", configuration.base_path, id = p_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FreezeLog`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FreezeLog`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFreezeLogFreezeLogsIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get all `freeze logs` for the given filter parameters
pub async fn list_freeze_logs_freeze_logs_get(
    configuration: &configuration::Configuration,
    freeze_id: Option<i32>,
    student_id: Option<i32>,
    campus_id: Option<i32>,
    status: Option<&str>,
    begin_date: Option<String>,
    expected_end_date: Option<String>,
    created_at: Option<String>,
    effective_end_date: Option<String>,
    approved_at: Option<String>,
    triggered_by: Option<&str>,
    ts: Option<String>,
    page: Option<i32>,
    size: Option<i32>,
) -> Result<models::PageFreezeLog, Error<ListFreezeLogsFreezeLogsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_freeze_id = freeze_id;
    let p_student_id = student_id;
    let p_campus_id = campus_id;
    let p_status = status;
    let p_begin_date = begin_date;
    let p_expected_end_date = expected_end_date;
    let p_created_at = created_at;
    let p_effective_end_date = effective_end_date;
    let p_approved_at = approved_at;
    let p_triggered_by = triggered_by;
    let p_ts = ts;
    let p_page = page;
    let p_size = size;

    let uri_str = format!("{}/freeze_logs", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_freeze_id {
        req_builder = req_builder.query(&[("freeze_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_student_id {
        req_builder = req_builder.query(&[("student_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_campus_id {
        req_builder = req_builder.query(&[("campus_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_begin_date {
        req_builder = req_builder.query(&[("begin_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_expected_end_date {
        req_builder = req_builder.query(&[("expected_end_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_created_at {
        req_builder = req_builder.query(&[("created_at", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_effective_end_date {
        req_builder = req_builder.query(&[("effective_end_date", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_approved_at {
        req_builder = req_builder.query(&[("approved_at", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_triggered_by {
        req_builder = req_builder.query(&[("triggered_by", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_ts {
        req_builder = req_builder.query(&[("ts", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PageFreezeLog`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PageFreezeLog`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListFreezeLogsFreezeLogsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
