/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BonusDayUpdate {
    #[serde(rename = "milestone_id", deserialize_with = "Option::deserialize")]
    pub milestone_id: Option<i32>,
    #[serde(
        rename = "granted_bonus_days",
        deserialize_with = "Option::deserialize"
    )]
    pub granted_bonus_days: Option<i32>,
}

impl BonusDayUpdate {
    pub fn new(milestone_id: Option<i32>, granted_bonus_days: Option<i32>) -> BonusDayUpdate {
        BonusDayUpdate {
            milestone_id,
            granted_bonus_days,
        }
    }
}
