/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BonusDay {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "campus_id")]
    pub campus_id: i32,
    #[serde(rename = "milestone_id")]
    pub milestone_id: i32,
    #[serde(rename = "granted_bonus_days")]
    pub granted_bonus_days: i32,
}

impl BonusDay {
    pub fn new(id: i32, campus_id: i32, milestone_id: i32, granted_bonus_days: i32) -> BonusDay {
        BonusDay {
            id,
            campus_id,
            milestone_id,
            granted_bonus_days,
        }
    }
}
