/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampusCreate {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(
        rename = "max_freeze_days_per_student",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_freeze_days_per_student: Option<i32>,
    #[serde(
        rename = "freeze_min_duration",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_min_duration: Option<i32>,
    #[serde(
        rename = "max_freeze_occurences_per_student",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_freeze_occurences_per_student: Option<i32>,
    #[serde(rename = "default_bonus_days", skip_serializing_if = "Option::is_none")]
    pub default_bonus_days: Option<i32>,
    #[serde(
        rename = "auto_approval_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_approval_enabled: Option<bool>,
    #[serde(
        rename = "auto_approval_max_freeze_duration",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_approval_max_freeze_duration: Option<i32>,
    #[serde(rename = "is_activated", skip_serializing_if = "Option::is_none")]
    pub is_activated: Option<bool>,
    #[serde(
        rename = "custom_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_message: Option<Option<String>>,
    #[serde(
        rename = "pedago_mail_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub pedago_mail_address: Option<Vec<String>>,
    #[serde(
        rename = "bonus_days_settings",
        skip_serializing_if = "Option::is_none"
    )]
    pub bonus_days_settings: Option<Vec<models::BonusDay>>,
    #[serde(
        rename = "freeze_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "freeze_webhook_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_secret: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_secret: Option<Option<String>>,
}

impl CampusCreate {
    pub fn new(id: i32, name: String, timezone: String) -> CampusCreate {
        CampusCreate {
            id,
            name,
            timezone,
            max_freeze_days_per_student: None,
            freeze_min_duration: None,
            max_freeze_occurences_per_student: None,
            default_bonus_days: None,
            auto_approval_enabled: None,
            auto_approval_max_freeze_duration: None,
            is_activated: None,
            custom_message: None,
            pedago_mail_address: None,
            bonus_days_settings: None,
            freeze_webhook_uri: None,
            freeze_webhook_secret: None,
            user_webhook_uri: None,
            user_webhook_secret: None,
        }
    }
}
