/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampusUpdate {
    #[serde(
        rename = "max_freeze_days_per_student",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_freeze_days_per_student: Option<Option<i32>>,
    #[serde(
        rename = "freeze_min_duration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_min_duration: Option<Option<i32>>,
    #[serde(
        rename = "max_freeze_occurences_per_student",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_freeze_occurences_per_student: Option<Option<i32>>,
    #[serde(
        rename = "default_bonus_days",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_bonus_days: Option<Option<i32>>,
    #[serde(
        rename = "auto_approval_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_approval_enabled: Option<Option<bool>>,
    #[serde(
        rename = "auto_approval_max_freeze_duration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_approval_max_freeze_duration: Option<Option<i32>>,
    #[serde(
        rename = "custom_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_message: Option<Option<String>>,
    #[serde(
        rename = "freeze_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "freeze_webhook_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_secret: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_secret: Option<Option<String>>,
    #[serde(
        rename = "pedago_mail_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pedago_mail_address: Option<Option<Vec<String>>>,
}

impl CampusUpdate {
    pub fn new() -> CampusUpdate {
        CampusUpdate {
            max_freeze_days_per_student: None,
            freeze_min_duration: None,
            max_freeze_occurences_per_student: None,
            default_bonus_days: None,
            auto_approval_enabled: None,
            auto_approval_max_freeze_duration: None,
            custom_message: None,
            freeze_webhook_uri: None,
            user_webhook_uri: None,
            freeze_webhook_secret: None,
            user_webhook_secret: None,
            pedago_mail_address: None,
        }
    }
}
