/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Campus {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(rename = "max_freeze_days_per_student")]
    pub max_freeze_days_per_student: i32,
    #[serde(rename = "freeze_min_duration")]
    pub freeze_min_duration: i32,
    #[serde(rename = "max_freeze_occurences_per_student")]
    pub max_freeze_occurences_per_student: i32,
    #[serde(rename = "default_bonus_days")]
    pub default_bonus_days: i32,
    #[serde(rename = "auto_approval_enabled")]
    pub auto_approval_enabled: bool,
    #[serde(rename = "auto_approval_max_freeze_duration")]
    pub auto_approval_max_freeze_duration: i32,
    #[serde(rename = "is_activated")]
    pub is_activated: bool,
    #[serde(
        rename = "custom_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_message: Option<Option<String>>,
    #[serde(
        rename = "pedago_mail_address",
        skip_serializing_if = "Option::is_none"
    )]
    pub pedago_mail_address: Option<Vec<String>>,
    #[serde(rename = "bonus_days_settings")]
    pub bonus_days_settings: Vec<models::BonusDay>,
    #[serde(
        rename = "freeze_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "freeze_webhook_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_secret: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_secret: Option<Option<String>>,
}

impl Campus {
    pub fn new(
        id: i32,
        name: String,
        timezone: String,
        max_freeze_days_per_student: i32,
        freeze_min_duration: i32,
        max_freeze_occurences_per_student: i32,
        default_bonus_days: i32,
        auto_approval_enabled: bool,
        auto_approval_max_freeze_duration: i32,
        is_activated: bool,
        bonus_days_settings: Vec<models::BonusDay>,
    ) -> Campus {
        Campus {
            id,
            name,
            timezone,
            max_freeze_days_per_student,
            freeze_min_duration,
            max_freeze_occurences_per_student,
            default_bonus_days,
            auto_approval_enabled,
            auto_approval_max_freeze_duration,
            is_activated,
            custom_message: None,
            pedago_mail_address: None,
            bonus_days_settings,
            freeze_webhook_uri: None,
            freeze_webhook_secret: None,
            user_webhook_uri: None,
            user_webhook_secret: None,
        }
    }
}
