/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampusCustomMessage {
    #[serde(rename = "campus_id")]
    pub campus_id: i32,
    #[serde(rename = "custom_message")]
    pub custom_message: String,
}

impl CampusCustomMessage {
    pub fn new(campus_id: i32, custom_message: String) -> CampusCustomMessage {
        CampusCustomMessage {
            campus_id,
            custom_message,
        }
    }
}
