/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampusMailAddressUpdate {
    #[serde(
        rename = "pedago_mail_address_to_add",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pedago_mail_address_to_add: Option<Option<Vec<String>>>,
    #[serde(
        rename = "pedago_mail_address_to_remove",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pedago_mail_address_to_remove: Option<Option<Vec<String>>>,
}

impl CampusMailAddressUpdate {
    pub fn new() -> CampusMailAddressUpdate {
        CampusMailAddressUpdate {
            pedago_mail_address_to_add: None,
            pedago_mail_address_to_remove: None,
        }
    }
}
