/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CampusWebhookUpdate {
    #[serde(
        rename = "freeze_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub freeze_webhook_uri: Option<Option<String>>,
    #[serde(
        rename = "user_webhook_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_webhook_uri: Option<Option<String>>,
}

impl CampusWebhookUpdate {
    pub fn new() -> CampusWebhookUpdate {
        CampusWebhookUpdate {
            freeze_webhook_uri: None,
            user_webhook_uri: None,
        }
    }
}
