/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FreezeStudent {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "user")]
    pub user: Box<models::UserStudent>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Reason>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Category>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "is_free_freeze", skip_serializing_if = "Option::is_none")]
    pub is_free_freeze: Option<bool>,
    #[serde(rename = "begin_date")]
    pub begin_date: String,
    #[serde(rename = "expected_end_date")]
    pub expected_end_date: String,
    #[serde(
        rename = "effective_end_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_end_date: Option<Option<String>>,
    #[serde(
        rename = "student_description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub student_description: Option<Option<String>>,
    #[serde(
        rename = "staff_description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub staff_description: Option<Option<String>>,
    #[serde(
        rename = "approved_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub approved_by: Option<Option<String>>,
    #[serde(
        rename = "approved_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub approved_at: Option<Option<String>>,
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
    #[serde(
        rename = "updated_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
}

impl FreezeStudent {
    pub fn new(
        id: i32,
        user: models::UserStudent,
        begin_date: String,
        expected_end_date: String,
    ) -> FreezeStudent {
        FreezeStudent {
            id,
            user: Box::new(user),
            reason: None,
            category: None,
            status: None,
            is_free_freeze: None,
            begin_date,
            expected_end_date,
            effective_end_date: None,
            student_description: None,
            staff_description: None,
            approved_by: None,
            approved_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "medical")]
    Medical,
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "professional")]
    Professional,
    #[serde(rename = "other")]
    Other,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::Medical
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Category {
    #[serde(rename = "regular")]
    Regular,
    #[serde(rename = "bonus")]
    Bonus,
    #[serde(rename = "compensation")]
    Compensation,
}

impl Default for Category {
    fn default() -> Category {
        Self::Regular
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "ongoing")]
    Ongoing,
    #[serde(rename = "finished")]
    Finished,
    #[serde(rename = "reverted")]
    Reverted,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
