/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FreezeLog {
    #[serde(rename = "freeze_id")]
    pub freeze_id: i32,
    #[serde(rename = "student_id")]
    pub student_id: i32,
    #[serde(rename = "campus_id")]
    pub campus_id: i32,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "begin_date")]
    pub begin_date: String,
    #[serde(rename = "expected_end_date")]
    pub expected_end_date: String,
    #[serde(
        rename = "effective_end_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_end_date: Option<Option<String>>,
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
    #[serde(
        rename = "approved_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub approved_at: Option<Option<String>>,
    #[serde(
        rename = "triggered_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub triggered_by: Option<Option<String>>,
    #[serde(rename = "ts")]
    pub ts: String,
}

impl FreezeLog {
    pub fn new(
        freeze_id: i32,
        student_id: i32,
        campus_id: i32,
        status: Status,
        begin_date: String,
        expected_end_date: String,
        ts: String,
    ) -> FreezeLog {
        FreezeLog {
            freeze_id,
            student_id,
            campus_id,
            status,
            begin_date,
            expected_end_date,
            effective_end_date: None,
            created_at: None,
            approved_at: None,
            triggered_by: None,
            ts,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "ongoing")]
    Ongoing,
    #[serde(rename = "finished")]
    Finished,
    #[serde(rename = "reverted")]
    Reverted,
}

impl Default for Status {
    fn default() -> Status {
        Self::Approved
    }
}
