/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FreezeStaffActionDescription {
    #[serde(
        rename = "staff_description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub staff_description: Option<Option<String>>,
}

impl FreezeStaffActionDescription {
    pub fn new() -> FreezeStaffActionDescription {
        FreezeStaffActionDescription {
            staff_description: None,
        }
    }
}
