/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageCampus {
    #[serde(rename = "items")]
    pub items: Vec<models::Campus>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(
        rename = "pages",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pages: Option<Option<i32>>,
}

impl PageCampus {
    pub fn new(items: Vec<models::Campus>, total: i32, page: i32, size: i32) -> PageCampus {
        PageCampus {
            items,
            total,
            page,
            size,
            pages: None,
        }
    }
}
