/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserStudent {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "campus")]
    pub campus: Box<models::CampusStudent>,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "available_bonus_days")]
    pub available_bonus_days: i32,
    #[serde(
        rename = "mail_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mail_address: Option<Option<String>>,
    #[serde(rename = "used_freeze_days")]
    pub used_freeze_days: i32,
    #[serde(rename = "total_freeze_occurences")]
    pub total_freeze_occurences: i32,
    #[serde(rename = "is_freeze")]
    pub is_freeze: bool,
    #[serde(rename = "is_activated")]
    pub is_activated: bool,
    #[serde(
        rename = "cursus_begin_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cursus_begin_date: Option<Option<String>>,
    #[serde(
        rename = "anonymized_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub anonymized_at: Option<Option<String>>,
}

impl UserStudent {
    pub fn new(
        id: i32,
        campus: models::CampusStudent,
        login: String,
        available_bonus_days: i32,
        used_freeze_days: i32,
        total_freeze_occurences: i32,
        is_freeze: bool,
        is_activated: bool,
    ) -> UserStudent {
        UserStudent {
            id,
            campus: Box::new(campus),
            login,
            available_bonus_days,
            mail_address: None,
            used_freeze_days,
            total_freeze_occurences,
            is_freeze,
            is_activated,
            cursus_begin_date: None,
            anonymized_at: None,
        }
    }
}
