/*
 * Intra v3 - Freeze
 *
 * API for Freeze management for staff and students
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCreate {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "campus_id")]
    pub campus_id: i32,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(
        rename = "mail_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mail_address: Option<Option<String>>,
    #[serde(
        rename = "available_bonus_days",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_bonus_days: Option<i32>,
    #[serde(rename = "used_freeze_days", skip_serializing_if = "Option::is_none")]
    pub used_freeze_days: Option<i32>,
    #[serde(
        rename = "total_freeze_occurences",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_freeze_occurences: Option<i32>,
    #[serde(rename = "is_freeze", skip_serializing_if = "Option::is_none")]
    pub is_freeze: Option<bool>,
    #[serde(rename = "is_activated", skip_serializing_if = "Option::is_none")]
    pub is_activated: Option<bool>,
    #[serde(
        rename = "cursus_begin_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cursus_begin_date: Option<Option<String>>,
}

impl UserCreate {
    pub fn new(id: i32, campus_id: i32, login: String) -> UserCreate {
        UserCreate {
            id,
            campus_id,
            login,
            mail_address: None,
            available_bonus_days: None,
            used_freeze_days: None,
            total_freeze_occurences: None,
            is_freeze: None,
            is_activated: None,
            cursus_begin_date: None,
        }
    }
}
